name: recursive_reasoning.trm_fvr_kstream@TinyRecursiveReasoningModel_ACTV1
loss:
  name: losses_fvr@FVRACTLossHead
  loss_type: stablemax_cross_entropy
  lambda_aux: 0.3
  lam_hsic: 0.0
  lam_cov: 0.0
  lam_var: 0.0
  gamma: 1.0

halt_exploration_prob: 0.1
halt_max_steps: 16

H_cycles: 3
L_cycles: 6

H_layers: 0
L_layers: 2

hidden_size: 512
num_heads: 8
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
forward_dtype: bfloat16

mlp_t: False
puzzle_emb_len: 16
no_ACT_continue: True

K: 4
agg_init_value: 0.0
